### ISSUE TITLE
Need update

### ISSUE THREAD

**Issue by M829A3** [diwako/ACRE2-Custom-Signal-Calculation#2]
The entire functionality of this script seems to have been disabled with the ACRE2 update. I really like the functionality of this script and hope to be able to use it in my missions sooner rather than later.

**Comment by diwako** [comment]
Hey. Are there any error thrown? What exactly does not work, does ACRE work as normal or doesn't it work at all anymore?

I do need more info than "does not work"

**Comment by diwako** [comment]
While I actually found not an issue with the current version. I restructured it and made it more maintainable. Tested its functionality as well to make sure it works.

You can try out this one. right now it is in another branch
https://github.com/diwako/ACRE2-Custom-Signal-Calculation/tree/restructure

**Comment by diwako** [comment]
PR: #3

**Comment by M829A3** [comment]
Sorry for the late reply. I ran a simple test with a dozen players on a dedicated server, I tried the Radio jammers feature but our 343 and 152 still communicate properly.
[jammer_1, 5000, [50,2410], 400, 300] call diw_acre_fnc_createRadioJammer;

In addition I tried the crippling radios feature, I adjusted the player's radio transceiver capability to 0, and we still had normal communication.

I didn't get any error messages throughout the process, so I guess ACRE2 changed the radio signal transmission mechanism in the update? My English is not very good, if you do not understand anything, please ask me again.

**Comment by M829A3** [comment]
I'll be trying out the new version of the script, thanks for the outstanding work!

**Comment by diwako** [comment]
So anything new @M829A3 ?
